name: Deploy
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Enable dry run mode (true or false)'
        required: true
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - { local: ./src/web-file-browser-api, server: ${{ vars.SRC_DIR }} }
          - { local: ./public/web-file-browser-api, server: ${{ vars.PUBLIC_DIR }} }
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Directory
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ matrix.directory.local }}
          server-dir: ${{ matrix.directory.server }}
          dry-run: ${{ inputs.dry-run || false }}
